#!/bin/sh

# Extract archives with ex
ex () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1 -d "${1%%.*}";;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# This function will:
# 1) auto-cd if given a directory instead of a file
# 2) Automatically request root permissions if the user isn't able to modify the file
# It's a small QOL improvement since I always use vim on a directory or root file.
vim () {
    if [ -d "$1" ]; then
        cd "$1" || exit
    elif [ -f "$1" ]; then
        if groups | grep -q "$(stat -c "%G" "$1")"; then
            nvim "$1"
        else
            sudo nvim "$1"
        fi
    else
        echo "file does not exist"
    fi
}


# Shorten name
alias mutt='neomutt'

# ls aliases
alias ls='ls --color=auto'
alias ll='ls -llh'
alias la='ls -llha'
# MORE SPEED
alias sl='ls'

# File management aliases
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'

# Source zshrc
alias zs='source ~/.config/zsh/.zshrc'

# Quick cd aliases
alias cdb='cd ~/.local/bin'
alias cdu='cd ~/Documents/Dev/Sketches/unified'

# Edit files
alias ic='vim ~/.config/i3/config && i3-msg restart'
alias sc='vim ~/.config/sway/config && swaymsg reload'
alias pc='vim ~/.config/polybar/config'
alias pca='vim ~/.config/polybar/config.alt'
alias cc='vim ~/.config/picom.conf'
alias kc='vim ~/.config/kitty/kitty.conf'
alias zc='vim ~/.config/zsh/.zshrc && source ~/.config/zsh/.zshrc'
alias vc='vim ~/.config/nvim/init.vim'
alias tc='vim ~/.tmux.conf && tmux source-file ~/.tmux.conf'
alias ac='vim ~/.config/aliasrc && source ~/.config/aliasrc'
alias bsc='vim ~/.config/bspwm/bspwmrc'
alias sxc='vim ~/.config/sxhkd/sxhkdrc'

# yay-like pacman alias
alias pin='sudo pacman -Syu'

# Quit
alias :q='exit'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit -m '
alias gp='git push'
alias gd='git diff'
alias DF='git -C ~/.dot'
alias ds='DF status'
alias da='DF add'
alias dc='DF commit -m '
alias dp='DF push'
alias DU='DF fetch --all && DF reset --hard origin/master'
alias weather="curl -s 'wttr.in/?format=%C+%t&$ACTIVE' | sed 's/\s*//g'"

# Sync website
alias websync='rsync -av --update ~/Documents/Dev/web-html/ root@vultr:/var/www/site/'

# Misc
alias wid="xprop WM_CLASS"
alias ddd="sudo dd bs=2M status=progress"
# systemctl aliases
alias SS="sudo systemctl"
alias SSDR="sudo systemctl daemon-reload"
alias SU="systemctl --user"
# VFIO aliases
alias lsvfio="lspci -nnk | grep 'Kernel driver in use: vfio-pci' -B 2"
alias lsevdev="ls /dev/input/by-id"

# Keypads
alias u2k="pio run -e 2k -t upload -d ~/Documents/Dev/Sketches/trinketM0"
alias u4k="pio run -e 4k -t upload -d ~/Documents/Dev/Sketches/trinketM0"
alias u7k="pio run -t upload -d ~/Documents/Dev/Sketches/7kKeypad"
alias uM="pio run -t upload -d ~/Documents/Dev/Sketches/trinketM0Macro"
alias u2kt="pio run -e 2k -t upload -d ~/Documents/Dev/Sketches/touchPad"
alias u4kt="pio run -e 4k -t upload -d ~/Documents/Dev/Sketches/touchPad"
alias pdm="pio device monitor -f printable -f send_on_enter"

# Run vim as root with user config
alias svim="sudo -E vim"
