#! /bin/sh

~/.config/polybar/launch.sh 1 &
sxhkd &
sxhkd -c ~/.config/sxhkd/bspwm.sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor HDMI1 -d 1 2
#bspc desktop -f '^{1-2}' && bspc config split_ratio 0.33

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color "#1c1f26"
bspc config focused_border_color "#bf616a"
bspc config active_border_color "#2b303b"
bspc config presel_presel_color "#2b303b"
