#!/bin/sh

while read file
do
    EXT=$(echo $file | awk -F "." '{print $NF}')
    case "$1" in
    "C-c")
        xclip -selection clipboard -t image/$TYPE -i $file ;;
    "C-1")
        # Convert file to png if not already
        [ $EXT != "png" ] && convert $file ~/.config/wall.png || cp $file ~/.config/wall.png
        # Set two wallpapers if two monitors are connected
        [ $(xrandr | grep " connected" | wc -l) -eq 2 ] && feh --bg-fill ~/.config/wall.png ~/.config/wall2.png || feh --bg-fill ~/.config/wall.png
        ;;
    "C-2")
        [ $EXT != "png" ] && convert $file ~/.config/wall2.png || cp $file ~/.config/wall2.png
        feh --bg-fill ~/.config/wall.png ~/.config/wall2.png
        ;;
    esac
done
