#!/bin/sh

while read -r file
do
    EXT=$(echo "$file" | awk -F "." '{print $NF}')
    case "$1" in
    # Press ctrl+c to copy the file to the clipboard
    "C-c")
        xclip -selection clipboard -t "image/$EXT" -i "$file";;
    # ctrl+1 to set the wallpaper for monitor 1
    "C-1")
        # Make a copy of the file in config folder
        mkdir -p ~/.config/walls 2>/dev/null
        cp "$file" ~/.config/walls
        # Convert file to png if not already
        if [ "$EXT" != "png" ]; then
            convert "$file" ~/.config/wall.png
        else
            cp "$file" ~/.config/wall.png
        fi
        # Set two wallpapers if two monitors are connected
        if [ "$(xrandr | grep -c " connected")" -eq 2 ]; then
            feh --bg-fill ~/.config/wall.png ~/.config/wall2.png
        else
            feh --bg-fill ~/.config/wall.png
        fi
        ;;
    # ctrl+2 to set the wallpaper for monitor 2
    "C-2")
        if [ "$EXT" != "png" ]; then
            convert "$file" ~/.config/wall2.png
        else
            cp "$file" ~/.config/wall2.png
        fi
        feh --bg-fill ~/.config/wall.png ~/.config/wall2.png
        ;;
    esac
done
